application: djangae-testapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /media
  static_dir: static/media/

- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /.*
  script: testapp.wsgi.application

skip_files:
- ^(.*/)?.*\.py[co~]
- (.*~)
- (\..*)
- (app\.yaml)
- (index\.yaml)
