application: djangae-testapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /media
  static_dir: static/media/

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /.*
  script: djangae.wsgi.main

skip_files: 
- google_appengine(.*/)?
- ^(.*/)?.*\.py[co~]
- (.*~)
- (\..*)
- (app\.yaml)
- (index\.yaml)

